apiVersion: kudo.dev/v1beta1
parameters:
  - name: HOST_NAME
    description: "Host name used to generate absolute URLs in responses"
    default: "localhost"
  - name: SCHEMA_REGISTRY_URL
    description: "The base URL for Schema Registry that should be used by the Avro serializer"
    default: "http://localhost:8081/"
  - name: REST_PROXY_PORT
    description: "Port on which Confluent REST PROXY will be exported"
    default: 8082
  - name: MEMORY
    description: Amount of memory to provide to Zookeeper pods
    default: "256Mi"
  - name: MEM_LIMIT
    description: "Memory (limit) for the Zookeeper nodes pods. spec.containers[].resources.limits.memory"
    default: "1024Mi"
  - name: CPUS
    description: Amount of cpu to provide to Zookeeper pods
    default: "250m"
  - name: CPUS_LIMIT
    description: "CPUs (limit) for the Zookeeper nodes pods. spec.containers[].resources.limits.cpu"
    default: "1000m"