apiVersion: kudo.dev/v1beta1
parameters:
  - name: HOST_NAME
    description: "Host name used to generate absolute URLs in responses"
    default: "localhost"
  - name: SCHEMA_REGISTRY_URL
    description: "The base URL for Confluent Schema Registry that should be used by the Avro serializer"
    default: "http://localhost:8081/"
  - name: KAFKA_BOOTSTRAP_SERVERS
    description: "A list of Kafka brokers to connect to. Eg. PLAINTEXT://hostname:9092"
    default: "kafka-kafka-0.kafka-svc.default.svc.cluster.local:9093,kafka-kafka-1.kafka-svc.default.svc.cluster.local:9093,kafka-kafka-2.kafka-svc.default.svc.cluster.local:9093"
  - name: REST_PROXY_PORT
    description: "Port on which Confluent REST Proxy will be exported to listen on for new connections"
    default: 8082
  - name: MEMORY
    description: "Amount of memory to provide to Confluent REST Proxy pods"
    default: "256Mi"
  - name: MEM_LIMIT
    description: "Memory (limit) for the Confluent REST Proxy nodes pods. spec.containers[].resources.limits.memory"
    default: "1024Mi"
  - name: CPUS
    description: Amount of cpu to provide to Confluent REST Proxy pods
    default: "250m"
  - name: CPUS_LIMIT
    description: "CPUs (limit) for the Confluent REST Proxy nodes pods. spec.containers[].resources.limits.cpu"
    default: "1000m"
  - name: DISK_SIZE
    description: "Disk size for the Confluent REST Proxy servers"
    default: "1Gi"
    trigger: "not-allowed"
  - name: STORAGE_CLASS
    description: "The storage class to be used in volumeClaimTemplates. By default its not required and the default storage class is used."
    required: false
    trigger: "not-allowed"
