apiVersion: kudo.dev/v1beta1
parameters:
  - name: HOST_NAME
    description: "Host name used to generate absolute URLs in responses"
    default: "localhost"
  - name: SCHEMA_REGISTRY_URL
    description: "The base URL for Schema Registry that should be used by the Avro serializer"
    default: "http://localhost:8081/"
  - name: REST_PROXY_PORT
    description: "Port on which Confluent REST PROXY will be exported"
    default: 8082